services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  onemarshall\AosBundle\EventListener\HookListener:
    arguments:
      - "@request_stack"
      - "@contao.routing.scope_matcher"
